// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using N5API.Infraestructure.DataPersistence;

#nullable disable

namespace N5API.Infraestructure.Migrations
{
    [DbContext(typeof(PermissionContext))]
    partial class PermissionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("N5API.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaPermiso");

                    b.Property<string>("ForeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreEmpleado");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("TipoPermiso");

                    b.Property<int?>("PermissionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ApellidoEmpleado");

                    b.HasKey("Id");

                    b.HasIndex("PermissionTypeId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 7, 26, 9, 27, 38, 730, DateTimeKind.Local).AddTicks(5718),
                            ForeName = "ForeName 1 ",
                            PermissionId = 1,
                            SurName = "SurName 1 "
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 7, 26, 9, 27, 38, 730, DateTimeKind.Local).AddTicks(5730),
                            ForeName = "ForeName 2 ",
                            PermissionId = 1,
                            SurName = "SurName 2 "
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 7, 26, 9, 27, 38, 730, DateTimeKind.Local).AddTicks(5732),
                            ForeName = "ForeName 3 ",
                            PermissionId = 2,
                            SurName = "SurName 3 "
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 7, 26, 9, 27, 38, 730, DateTimeKind.Local).AddTicks(5733),
                            ForeName = "ForeName 4 ",
                            PermissionId = 3,
                            SurName = "SurName 4 "
                        });
                });

            modelBuilder.Entity("N5API.Domain.Entities.PermissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("PermissionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Permission Type 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Permission Type 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Permission Type 3"
                        });
                });

            modelBuilder.Entity("N5API.Domain.Entities.Permission", b =>
                {
                    b.HasOne("N5API.Domain.Entities.PermissionType", "PermissionType")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionTypeId");

                    b.Navigation("PermissionType");
                });

            modelBuilder.Entity("N5API.Domain.Entities.PermissionType", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
